Lammps
alchemistry/alchemtest pull request #96
Opened 2024-12-11 01:07 UTC by jaclark5

## Description
Add data set to test LAMMPS parser

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [X] Add lammps dataset with description
  - [X] Add tests
  - [X] Add documentation

## Status
- [X] Ready to go

2024-12-15 01:02 UTC, jaclark5 commented
@xiki-tempula are you the one to request a review from?

2024-12-18 15:41 UTC, xiki-tempula requested changes
small comments.
Have you read https://alchemtest.readthedocs.io/en/latest/contributing.html and check this PR has done all of the things listed?
Have you download the branch as a archive zip and check that the files are there? (Sometimes test files are not packed properly in the zip)

2024-12-18 15:41 UTC, xiki-tempula commented on docs/index.rst
> +    gmx
Duplication?

2024-12-19 02:30 UTC, jaclark5 commented
Hey @xiki-tempula  I reread the contributing document and noticed that the directions to compile the docs don't align.

I've also compressed the text files and fixed that issue with the docs that you noted.

2024-12-20 14:30 UTC, xiki-tempula approved these changes
LGTM thanks

2024-12-20 14:30 UTC, merged